const externals = {
  apps: [
    { path: 'dashboard', entry: 'Dashboard' },
    { path: 'model-catalogue', entry: 'ModelCatalogue' },
    { path: 'model-info', entry: 'ModelInfo' },
    { path: 'training-packages', entry: 'TrainingPackages' },
    { path: 'training-jobs', entry: 'TrainingJobs' },
    { path: 'training-package-detail', entry: 'TrainingPackageDetail' },
    { path: 'model-services', entry: 'ModelServices' },
    { path: 'model-service-detail', entry: 'ModelServiceDetail' },
    { path: 'settings', entry: 'Settings' },
    { path: 'notebooks', entry: 'Notebooks' },
  ],
  components: {
    default: [{ path: 'settings-icon', entry: 'Main' }],
    shareable: [
      { path: 'dashboard/gauge-chart-component', entry: 'GaugeChartComponent' },
      { path: 'dashboard/tile-info-component', entry: 'TileInfoComponent' },
      { path: 'model-list/model-container', entry: 'ModelContainer' },
      { path: 'model-list/model-card', entry: 'ModelCard' },
      { path: 'model-list/model-list', entry: 'ModelList' },
      { path: 'model-list/model-table', entry: 'ModelTable' },
      { path: 'model-list/model-versions', entry: 'ModelVersions' },
      { path: 'notebooks/notebook-container', entry: 'NotebookContainer' },
      { path: 'notebooks/notebook-card', entry: 'NotebookCard' },
      { path: 'notebooks/notebook-table', entry: 'NotebookTable' },
      { path: 'notebooks/notebook-list', entry: 'NotebookList' },
      { path: 'notebooks/create-notebook', entry: 'CreateNotebook' },
      { path: 'training-packages/package-container', entry: 'PackageContainer' },
      { path: 'training-packages/package-details', entry: 'PackageDetails' },
      { path: 'training-packages/package-list', entry: 'PackageList' },
      { path: 'training-packages/package-versions', entry: 'PackageVersions' },
      { path: 'training-packages/package-card', entry: 'PackageCard' },
      { path: 'training-packages/package-table', entry: 'PackageTable' },
      { path: 'training-jobs/job-container', entry: 'JobContainer' },
      { path: 'training-jobs/job-table', entry: 'JobTable' },
      { path: 'model-services/services-container', entry: 'ServicesContainer' },
      { path: 'model-services/services-table', entry: 'ServicesTable' },
      { path: 'model-services/service-detail', entry: 'ServiceDetail' },
      { path: 'model-services/service-detail/service-models', entry: 'ServiceModels' },
      { path: 'shared/create-model-service', entry: 'CreateModelService' },
      { path: 'shared/model-selector', entry: 'ModelSelector' },
      { path: 'shared/change-model', entry: 'ChangeModel' },
      { path: 'shared/custom-table', entry: 'CustomTable' },
      { path: 'shared/sidebar', entry: 'Sidebar' },
      { path: 'shared/upload-component', entry: 'UploadComponent' },
      { path: 'shared/upload-component-with-input', entry: 'UploadComponentWithInput' },
      { path: 'shared/model-details', entry: 'ModelDetails' },
      { path: 'shared/model-details/model-information', entry: 'ModelInformation' },
      { path: 'shared/model-details/monitoring-information', entry: 'MonitoringInformation' },
      { path: 'shared/model-details/contained-services', entry: 'ContainedServices' },
      { path: 'shared/model-details/invoke-model', entry: 'InvokeModel' },
      { path: 'shared/model-details/custom-metrics', entry: 'CustomMetrics' },
      { path: 'shared/monitoring-line-chart', entry: 'MonitoringLineChart' },
      { path: 'shared/chart-legend', entry: 'ChartLegend' },
      { path: 'shared/gauge-chart', entry: 'GaugeChart' },
      { path: 'shared/error-screen', entry: 'ErrorScreen' },
      { path: 'shared/list-sorting', entry: 'ListSorting' },
      { path: 'shared/filter-pill', entry: 'FilterPill' },
      { path: 'shared/view-change', entry: 'ViewChange' },
      { path: 'settings/author-list', entry: 'AuthorList' },
      { path: 'shared/model-selector-container', entry: 'ModelSelectorContainer' },
      { path: 'shared/model-tabs', entry: 'ModelTabs' },
      { path: 'shared/line-chart-component', entry: 'LineChartComponent' },
      { path: 'shared/service-scaling', entry: 'ServiceScaling' },
      { path: 'model-services/service-logs', entry: 'ServiceLogs' },
    ],
  },
  panels: [
    { path: 'notification-panel', entry: 'NotificationPanel' },
    { path: 'left-menu-panel', entry: 'LeftMenuPanel' },
    { path: 'user-settings-panel', entry: 'UserSettingsPanel' },
  ],
  plugins: [
    { path: 'notifications', entry: 'index' },
    { path: 'authentication', entry: 'index' },
    { path: 'error-handler', entry: 'index' },
    { path: 'loading', entry: 'index' },
    { path: 'apps-handler', entry: 'index' },
    { path: 'options-handler', entry: 'index' },
  ],
};

module.exports = externals;
