{{- if not .Values.minio.userSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-mxe-argo.minio-user-secret-name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: argo-service-minio-user-secret"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-argo.minio-user-secret-name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-argo.labels" . | fromYaml -}}
    {{- include "eric-mxe-argo.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: pre-install"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-argo.hook-weight" -5 | fromYaml -}}
    {{- $annotations := include "eric-mxe-argo.annotations" . | fromYaml -}}
    {{- include "eric-mxe-argo.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
type: Opaque
data:
  accesskey: {{ include "eric-mxe-argo.minio-user-name" . | quote }}
  {{- if .Values.minio.userSecretkey }}
  secretkey: {{ .Values.minio.userSecretkey | b64enc | quote }}
  {{- else }}
  secretkey: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
