apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "eric-mxe-argo.workflow-roletype" .}}
metadata:
  name: {{ include "eric-mxe-argo.workflow-role" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: argo-workflow-role"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-argo.workflow-role" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-argo.labels" . | fromYaml -}}
    {{- include "eric-mxe-argo.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-argo.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowartifactgctasks
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowartifactgctasks/status
    verbs:
      - patch
  - apiGroups:
      - "sparkoperator.k8s.io"
    resources:
      - sparkapplications
      - scheduledsparkapplications
    verbs:
      - get
      - patch
      - watch
      - create
      - update
      - list