apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-mxe-argo.workflow-service-account" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: argo-workflow-service-account"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-argo.workflow-service-account" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-argo.labels" . | fromYaml -}}
    {{- include "eric-mxe-argo.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-argo.annotations" . | nindent 4 }}
