apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-mxe-default-backend.fullname" . | quote }}
  labels:
    {{- include "eric-mxe-default-backend.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-mxe-default-backend.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [ {{ .Values.global.internalIPFamily | quote }} ]
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "default-backend"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
