kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "mxe-commons.keycloak-oauth-ingress.name" . | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "eric-sec-access-mgmt-oauth"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-commons.keycloak-oauth-ingress.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-commons.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    mxe.nginx.ingress.kubernetes.io/service-upstream: "true"
    mxe.nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.keycloak.service.name }}
    {{- include "mxe-commons.product-info" . | nindent 4 }}    
spec:
  ingressClassName: {{ index .Values "keycloak" "ingress" "class" | quote }}
  rules:
    - http:
        paths:
          - path: "/auth"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.keycloak.service.name }}
                port:
                  number: {{ include "mxe-commons.iam-port" . }}
      host: {{ include "mxe-commons.oauth-api-host" . | quote }}