apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mxe-commons.log-control-configmap" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "log-control-configmap"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-commons.log-control-configmap" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-commons.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    {{- include "mxe-commons.product-info" . | nindent 4 }}
data:
  logcontrol.json: |-
    [
        {
          "container": "eric-mxe-model-training-service",
          "severity": "info"
        },
        {
          "container": "eric-mxe-model-catalogue-service",
          "severity": "info"
        },
        {
          "container": "eric-mxe-model-service",
          "severity": "info"
        },
        {
          "container": "mxe-commons-author-service",
          "severity": "info"
        }

    ]
