apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mxe-commons.docker-registry-secret-name" . | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "mxe-docker-registry-secret"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-commons.docker-registry-secret-name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-commons.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    {{- include "mxe-commons.product-info" . | nindent 4 }}
type: Opaque
data:
  # Changed the logic to generate htpasswd from random password using the Helm sprig function htpasswd
  # instead of reading from files/htpasswd file in the chart.
  htpasswd: |-
    {{- htpasswd .Values.global.internalRegistry.username .Values.global.internalRegistry.password | b64enc | nindent 4 }}
