apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mxe-commons.pg-secret-name" . | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "mxe-pg-secret"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-commons.pg-secret-name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-commons.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    {{- include "mxe-commons.product-info" . | nindent 4 }}
type: Opaque
data:
  # For custom user and password
  custom-user: {{ "custom-postgres" | b64enc | quote }}
  {{- if .Values.config.pg.custom.password }}
  custom-pwd: {{ .Values.config.pg.custom.password | b64enc | quote }}
  {{- else }}
  custom-pwd: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
   # For super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  super-pwd: {{ "UG9zdGdyZXMxIw==" | quote }}
  # For metrics user and password
  metrics-user: {{ "exporter" | b64enc | quote }}
  metrics-pwd: {{ "ZXhwb3J0ZXI=" | quote }}
  # For replication user and password
  replica-user: {{ "replica" | b64enc | quote }}
  replica-pwd: {{ "cmVwbGljYQ==" | quote }}
