# Default values for eric-mxe-model-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

    
replicaCount: 1

nameOverride: null

isExtCA: false

ingress:
  enabled: true
  hostname: null
  secretName: null
  ingressClass: eric-mxe-ingress-controller-class
  annotationPrefix: null
  defaultBackendFullNameOverride: null
  defaultBackendNameOverride: null
  owasp:
    enabled: true

seldon:
  crd:
    nameOverride:
  engine:
    serviceAccount:
      nameOverride:

service:
  type: ClusterIP
  port: 8080
  metrics: 8081
  seldonModelMetrics: 6000

dockerRegistry:
  secretNameOverride: mxe-pull-secret
  externalHostname:
  externalPort: 32222

modelCatalogueService:
  # serviceNameOverride:
  portName: "http"

resources:
  modelService:
    requests:
      cpu: 100m
      memory: 1Gi
      ephemeral-storage: 50Mi
    limits:
      cpu: 300m
      memory: 2Gi
      ephemeral-storage: 100Mi
  cacerts:
    limits:
      cpu: 50m
      ephemeral-storage: 50Mi
      memory: 100Mi
    requests:
      cpu: 50m
      ephemeral-storage: 50Mi
      memory: 100Mi
  kubernetesModifier:
    limits:
      cpu: 50m
      ephemeral-storage: 50Mi
      memory: 100Mi
    requests:
      cpu: 50m
      ephemeral-storage: 50Mi
      memory: 100Mi

nodeSelector: {}

tolerations: []

topologySpreadConstraints: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/part-of"
                operator: "In"
                values:
                  - "mxe"
              - key: "app.kubernetes.io/component"
                operator: "In"
                values:
                  - "model-service"
              - key: "app.kubernetes.io/instance"
                operator: "In"
                values:
                  - "{{ .Release.Name }}"

imageCredentials:
  pullSecret:
  registry:
    url:
    pullSecret:
  repoPath:
  modelService:
    registry:
      url:
      pullSecret:
      imagePullPolicy:
    repoPath:
  kubernetes-modifier:
    registry:
      url:
      pullSecret:
      imagePullPolicy:
    repoPath:

productInfo:
  # R-State of the product. R State should match helm chart version (3.1.0 -> R2A)
  # To automate it when packaging the helm chart rstate can be generated
  # and below value replaced with correct R-State
  rstate: "-"

images:
  modelService:
    name: "mxe/eric-mxe-model-service"
    tag: "VERSION"
  kubernetes-modifier:
    name: "mxe/eric-mxe-kubernetes-modifier"
    tag: "VERSION"

tomcat:
  connectionTimeout: 60s

updateStrategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

keycloak:
  statefulset:
    name: eric-sec-access-mgmt

# DR-D1121-011 - Present in Top Level Helm Chart Values.yaml
#global:
#  pullSecret:
#  registry:
#    url: "armdocker.rnd.ericsson.se"
#    pullSecret:
#  mxeApiTlsSecretName:
#  mxeApiHostname:
#  mxeIamCaSecretName: iam-ca-cert
#  mxeDisableDefaultIngressControllerUse: false
#  internalRegistry:
#    username: admin
#    password: ""
#  labels: {}
#  annotations: {}


# Added to handle DR-D1121-068
labels: {}
annotations: {}

#Added to handle DR_D1120_012 & DR_D1120_014 & DR_D1120_080

probes:
  modelService:
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 30
      failureThreshold: 5
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 5
      timeoutSeconds: 5

podPriority:
  modelService:
    priorityClassName:

#Added to handle DR_D1120_080
terminationGracePeriodSeconds: 30

serviceMesh:
  enabled: true
  tlsMode: ISTIO_MUTUAL

# DR-D1123-127 -  ADP services shall define AppArmor profile
appArmorProfile:
  type:
  localhostProfile:

# DR-D1123-128 - ADP services shall define seccomp profile
seccompProfile:
  type: RuntimeDefault
  localhostProfile:

