{{- if .Values.mxeGitea.isExtCA -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "post-install-hook-external-certauth-job"
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "post-install-hook-external-certauth-job"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: "post-install-hook-external-certauth-job"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-deployer.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    {{- include "mxe-deployer.product-info" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        sidecar.istio.io/inject: "false"
    spec:
     {{- include "mxe-deployer.post-install-hook-certificate-externalcertauth-pull-secrets" . | nindent 6 }}
      serviceAccountName: "post-install-hook-external-certauth"
      containers:
        - name: "post-install-hook-external-certauth"
          image: "{{ include "mxe-deployer.post-install-hook-certificate-externalcertauth-repository" . }}{{ index .Values "mxePostInstallExtCertificate" "image" "name" }}:{{ index .Values "mxePostInstallExtCertificate" "image" "tag" }}"
          imagePullPolicy: "{{ include "mxe-deployer.post-install-hook.registryImagePullPolicy" (list . (index .Values "mxePostInstallExtCertificate" "image" "pullPolicy" )) }}"
          volumeMounts:
            - mountPath: "/etc/kubernetes-run-script/"
              name: kubernetes-run-script
            - mountPath: "/etc/patch-template/"
              name: patch-template
          env:
            - name: MXE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GITEA_SERVICE_NAME
              value: {{ include "mxe-deployer.gitea-service-name" . | quote }}
            - name: CONFIG_MAP_NAME
              value: "post-install-hook-external-certauth-configmap"
      restartPolicy: Never
      volumes:
      - name: kubernetes-run-script
        configMap:
          name: "post-install-hook-external-certauth-configmap"
          defaultMode: 0744
      - name: patch-template
        configMap:
          name: "post-install-hook-external-certauth-configmap-patchtemplate"
          defaultMode: 0744
{{- end -}}
