{{- if .Values.mxeGitea.isExtCA -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "post-install-hook-external-certauth"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "post-install-hook-external-certauth-service-account"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: "post-install-hook-external-certauth"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-deployer.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- include "mxe-deployer.product-info" . | nindent 4 }}
{{- end -}}
