{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mxe-gitea.gitea-keycloak-init" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "gitea-keycloak-init"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-gitea.gitea-keycloak-init" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/mxe-gitea/gitea-keycloak-init/run.sh").AsConfig | nindent 2 }}
{{- end }}