{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: mxe-gitea.rollout-restart-gitea
  namespace: {{ .Release.Namespace | quote }}  
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "rollout-restart-gitea"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: mxe-gitea.rollout-restart-gitea
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "post-upgrade"
    "helm.sh/hook-weight": "15"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        {{- include "mxe-gitea.security-annotations-gitea-restart" . | nindent 8 }}
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: mxe-gitea.rollout-restart-gitea
      containers:
        - name: rollout-restart-gitea
          image: "{{ include "mxe-gitea.wait-for-gitea.image-repository" . }}{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "name" }}:{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "tag" }}"
          imagePullPolicy: "{{ include "mxe-deployer-gitea.registryImagePullPolicy" (list . (index .Values "mxeGitea" "images" "kubernetes-modifier" "pullPolicy")) }}"
          command: ["/bin/sh","-c"]
          args: ["kubectl rollout restart deployment/mxe-deployer-gitea;kubectl rollout status deployment/mxe-deployer-gitea --watch"]
          env:
          - name: MXE_DEPLOYER_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          securityContext:
            {{- include "mxe-gitea.jobs-security-context" . | nindent 12 }}
      restartPolicy: Never    
      {{- include "mxe-gitea.gitea-create-user.image-pull-secrets" . | nindent 6 }}
{{- end }}