{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mxe-gitea.gitea-keycloak-init" . | quote }}
  namespace: {{ .Release.Namespace | quote }}  
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "gitea-keycloak-init"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-gitea.gitea-keycloak-init" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        {{- include "mxe-gitea.security-annotations-gitea-keycloak" . | nindent 8 }}
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ include "mxe-gitea.gitea-keycloak-init" . | quote }}
      containers:
        - name: gitea-keycloak-init
          image: "{{ include "mxe-gitea.gitea-keycloak-init.image-repository" . }}{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "name" }}:{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "tag" }}"
          imagePullPolicy: "{{ include "mxe-deployer-gitea.registryImagePullPolicy" (list . (index .Values "mxeGitea" "images" "kubernetes-modifier" "pullPolicy")) }}"
          volumeMounts:
            - mountPath: "/etc/kubernetes-run-script/"
              name: gitea-keycloak-init
          env:
            - name: MXE_DEPLOYER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KEYCLOAK_CONTAINER_NAME
              value: {{ .Values.mxeGitea.giteaKeycloakInit.keycloakContainerName | quote }}
            - name: KEYCLOAK_ADMIN_CLIENT
              value: {{ .Values.mxeGitea.giteaKeycloakInit.keycloakAdminClient | quote }}
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.mxeKeycloakAdminSecretName | quote }}
                  key: kcadminid
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.mxeKeycloakAdminSecretName | quote }}
                  key: kcpasswd
            - name: MXE_REALM
              value: {{ .Values.mxeGitea.giteaKeycloakInit.mxeRealm | quote }}
            - name: CLIENT_ID
              value: {{ .Values.mxeGitea.giteaKeycloakInit.clientId | quote }}
            - name: CLIENT_NAME
              value: {{ .Values.mxeGitea.giteaKeycloakInit.clientName | quote }}
            - name: CLIENT_REDIRECT_URI
              value: {{ .Values.mxeGitea.giteaKeycloakInit.clientRedirectUri | quote }}
            - name: AUTO_DISCOVERY_URL
              value: {{ .Values.mxeGitea.giteaKeycloakInit.autoDiscoveryUrl | quote }}
            - name: GITEA_AUTH_SOURCE_SECRET
              value: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthSourceSecret | quote }}
            - name: GITEA_AUTH_NAME
              value: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthName | quote }}
            - name: GITEA_AUTH_PROVIDER
              value: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthProvider | quote }}
            - name: SERVICE_MESH_MTLS_ENABLED
              value: {{ .Values.global.serviceMesh.enabled | quote }}
          securityContext:
            {{- include "mxe-gitea.jobs-security-context" . | nindent 12 }}
      restartPolicy: Never
      volumes:
      - configMap:
          name: {{ include "mxe-gitea.gitea-keycloak-init" . | quote }}
          defaultMode: 0744
        name: gitea-keycloak-init
      {{- include "mxe-gitea.gitea-keycloak-init.image-pull-secrets" . | nindent 6 }}
{{- end }}