{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mxe-gitea.gitea-create-auth-source" . | quote }}
  namespace: {{ .Release.Namespace | quote }}  
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "gitea-create-auth-source"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-gitea.gitea-create-auth-source" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        {{- include "mxe-gitea.security-annotations-gitea-auth" . | nindent 8 }}
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ include "mxe-gitea.gitea-create-auth-source" . | quote }}
      initContainers:
        - name: wait-for-gitea
          image: "{{ include "mxe-gitea.wait-for-gitea.image-repository" . }}{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "name" }}:{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "tag" }}"
          imagePullPolicy: "{{ include "mxe-deployer-gitea.registryImagePullPolicy" (list . (index .Values "mxeGitea" "images" "kubernetes-modifier" "pullPolicy")) }}"
          env:
            - name: MXE_DEPLOYER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: "/etc/kubernetes-run-script/"
              name: wait-for-gitea
          securityContext:
            {{- include "mxe-gitea.jobs-security-context" . | nindent 12 }}
      containers:
        - name: gitea-create-auth-source
          image: "{{ include "mxe-gitea.wait-for-gitea.image-repository" . }}{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "name" }}:{{ index .Values "mxeGitea" "images" "kubernetes-modifier" "tag" }}"
          imagePullPolicy: "{{ include "mxe-deployer-gitea.registryImagePullPolicy" (list . (index .Values "mxeGitea" "images" "kubernetes-modifier" "pullPolicy")) }}"
          env:
            - name: MXE_DEPLOYER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTH_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthSourceSecret | quote }}
                  key: authName
            - name: AUTH_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthSourceSecret | quote }}
                  key: authProvider                 
            - name: AUTO_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthSourceSecret | quote }}
                  key: autoDiscoveryUrl
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthSourceSecret | quote }}
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mxeGitea.giteaKeycloakInit.giteaAuthSourceSecret | quote }}
                  key: clientSecret                  
          volumeMounts:
            - name: gitea-create-auth-source
              readOnly: true
              mountPath: "/etc/kubernetes-run-script/" 
          securityContext:
            {{- include "mxe-gitea.jobs-security-context" . | nindent 12 }}                           
      restartPolicy: Never
      volumes:
      - configMap:
          name: {{ include "mxe-gitea.wait-for-gitea.name" . | quote }}
          defaultMode: 0744
        name: wait-for-gitea
      - configMap:
          name: {{ include "mxe-gitea.gitea-create-auth-source" . | quote }}
          defaultMode: 0744
        name: gitea-create-auth-source
      {{- include "mxe-gitea.gitea-create-auth-source.image-pull-secrets" . | nindent 6 }}
{{- end }}