{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mxe-gitea.gitea-create-auth-source" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "gitea-create-auth-source"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-gitea.gitea-create-auth-source" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - create
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - get
      - list
      - watch      
{{- end }}