{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mxe-gitea.pg-secret-name" . | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "mxe-pg-secret"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-gitea.pg-secret-name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
type: Opaque
data:
  # For super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  super-pwd: {{ "UG9zdGdyZXMxIw==" | quote }}
  # For gitea user and password
  gitea-user: {{ "gitea" | b64enc | quote }}
  gitea-pwd: {{ "WjJsMFpXRmZjR0Z6YzNkdmNtUT0=" | quote }}
{{- end }}