{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mxeGitea.admin.secret | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: {{ .Values.mxeGitea.admin.secret | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .Values.mxeGitea.admin.secret | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"    
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.gitea.gitea.admin.username | b64enc | quote }}
  password: {{ .Values.gitea.gitea.admin.password | b64enc | quote }}
  email: {{ .Values.gitea.gitea.admin.email | b64enc | quote }}
{{- end }}