{{- if .Values.internalGitopsRepoEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mxe-gitea.rollout-restart-gitea
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe-deployer"
    app.kubernetes.io/component: "rollout-restart-gitea"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: mxe-gitea.rollout-restart-gitea
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-gitea.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    {{- include "mxe-gitea.product-info" . | nindent 4 }}
{{- end }}