{{- if .Values.database.createCustomUserSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-mxe-author-service.db-custom-user-secret-name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: author-service-db"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-author-service.name" .)  | fromYaml -}}
    {{- $authSrvLabels := include "eric-mxe-author-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-author-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $authSrvLabels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-author-service.annotations" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.customUserIdKey }}: {{ include "eric-mxe-author-service.db-user-name" . | b64enc | quote }}
  {{- if .Values.database.customUserPwd }}
  {{ .Values.database.customUserPwdKey }}: {{ .Values.database.customUserPwd | b64enc | quote }}    
  {{- else }}
  {{ .Values.database.customUserPwdKey }}: {{ randAscii 24 | b64enc | quote }}
  {{- end }}  
{{- end }}
