{{- if .Values.global.serviceMesh.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "eric-mxe-author-service.name" . }}-dr
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: author-service"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-author-service.name" .)  | fromYaml -}}
    {{- $authSrvLabels := include "eric-mxe-author-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-author-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $authSrvLabels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-author-service.annotations" . | nindent 4 }}
spec:
  host: {{ include "eric-mxe-author-service.name" . }}
  trafficPolicy:
    tls:
      mode: {{ .Values.serviceMesh.tlsMode }}
{{ end }}