apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eric-mxe-author-service.role" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: author-service-role"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-author-service.name" .)  | fromYaml -}}
    {{- $authSrvLabels := include "eric-mxe-author-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-author-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $authSrvLabels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-author-service.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "create"
  - apiGroups:
      - "apps"
    resources:
      - "statefulsets"
    verbs:
      - "get"
      - "list"
      - "watch"
