apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-mxe-model-service.seldon-metrics-svc-name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-service"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-model-service.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-model-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-model-service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [ {{ .Values.global.internalIPFamily | quote }} ]
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.seldonModelMetrics }}
      targetPort: {{ .Values.service.seldonModelMetrics }}
      protocol: TCP
      name: metrics
      appProtocol: http
  selector:
    app.kubernetes.io/managed-by: seldon-core
