{{- if .Values.global.serviceMesh.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "eric-mxe-ingress-controller.name" . }}-dr
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: controller"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-ingress-controller.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-ingress-controller.labels" . | fromYaml -}}
    {{- include "eric-mxe-ingress-controller.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-ingress-controller.annotations" . | nindent 4 }}
spec:
  host: {{ include "eric-mxe-ingress-controller.name" . | quote }}
  trafficPolicy:
    tls:
      mode: {{ .Values.serviceMesh.tlsMode }}
{{ end }}