{{- if .Values.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-mxe-ingress-controller.serviceaccount" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: ingress-service-account"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-ingress-controller.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-ingress-controller.labels" . | fromYaml -}}
    {{- include "eric-mxe-ingress-controller.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-ingress-controller.annotations" . | nindent 4 }}
{{ end }}