{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-mxe-ingress-controller.name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: ingress-service"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-ingress-controller.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-ingress-controller.labels" . | fromYaml -}}
    {{- include "eric-mxe-ingress-controller.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-ingress-controller.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [ {{ .Values.global.internalIPFamily | quote }} ]
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "ingress-controller"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
{{ end }}
