{{- if .Values.global.serviceMesh.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "eric-mxe-ingress-controller.name" . }}-vs
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: controller"  | fromYaml -}}
    {{- $name := printf "%s: %s-%s" "app.kubernetes.io/name" (include "eric-mxe-ingress-controller.name" .) "vs" | fromYaml -}}
    {{- $labels := include "eric-mxe-ingress-controller.labels" . | fromYaml -}}
    {{- include "eric-mxe-ingress-controller.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-ingress-controller.annotations" . | nindent 4 }}
spec:
  hosts:
  - {{ default "*" .Values.global.mxeApiHostname . | quote }}
  gateways:
  - mesh
  http:
  - name: {{ include "eric-mxe-ingress-controller.name" . }}
    match:
    - uri:
        prefix: "/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ include "eric-mxe-ingress-controller.name" . }}
        port:
          number: 80
{{- end -}}