apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-mxe-deployer-service.authors-configmap" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: mxe-deployer-authors-configmap"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-deployer-service.authors-configmap" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-deployer-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-deployer-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-deployer-service.annotations" . | nindent 4 }}
data:
    {{ ( tpl (.Files.Glob "files/authorsconfig.yaml").AsConfig . ) | nindent 2 }}