{{- if .Values.ingress.enabled -}}
{{- $name := include "eric-mxe-deployer-service.name" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: mxe-deployer-ingress"  | fromYaml -}}
    {{- $nameLabel := printf "%s: %s" "app.kubernetes.io/name" $name  | fromYaml -}}
    {{- $labels := include "eric-mxe-deployer-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-deployer-service.mergeLabels" (dict "location" .Template.Name "sources" (list $nameLabel $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $annotations := include "eric-mxe-deployer-service.annotations" . | fromYaml -}}
    {{- $ingressAnn := .Values.ingress.annotations -}}
    {{- include "eric-mxe-deployer-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $ingressAnn $annotations )) | trim | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass | quote }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $name }}
              port: 
                number: {{ $svcPort }}
      {{- if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname | quote }}
      {{- end }}
  {{ if .Values.ingress.tlsSecretName -}}
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts:
        {{- if .Values.ingress.hostname }}
        - {{ .Values.ingress.hostname -}}
        {{- end }}
  {{ end -}}
{{- end }}
