apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-mxe-deployer-service.init-configmap" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: mxe-deployer-init-configmap"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-deployer-service.init-configmap" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-deployer-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-deployer-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-deployer-service.annotations" . | nindent 4 }}
data:
  run.sh: |
    {{- (.Files.Get "files/wait-for-argocdserver.sh") | nindent 4 }}
  oidcConfig.yaml: |
     {{- ( tpl (.Files.Get "files/argocdOIDCConfig.yaml") . ) | nindent 4 }}
  rbacConfig.yaml: |
     {{- ( tpl (.Files.Get "files/argocdRBACConfig.yaml") . ) | nindent 4 }}
  realmConfig.yaml: |
     {{- ( tpl (.Files.Get "files/argocdRealmConfig.yaml") . ) | nindent 4 }}
  repositoriesConfig.yaml: |
    {{- ( tpl (.Files.Get "files/argocdRepositoriesConfig.yaml") . ) | nindent 4 }}
  oidcTokenConfig.yaml: |
    {{- ( tpl (.Files.Get "files/keycloakTokenConfig.yaml") . ) | nindent 4 }}
