apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-mxe-deployer-service.rolebinding" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: mxe-deployer-rolebinding"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-deployer-service.rolebinding" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-deployer-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-deployer-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-deployer-service.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eric-mxe-deployer-service.role" . | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-mxe-deployer-service.serviceaccount" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
