# Default values for eric-mxe-gui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: null

service:
    type: ClusterIP
    port: 8080

ingress:
    enabled: true
    hostname: null
    secretName: null
    ingressClass: eric-mxe-ingress-controller-class
    annotationPrefix: null
    defaultBackendFullNameOverride: null
    defaultBackendNameOverride: null
    owasp:
        enabled: true

resources:
    gui:
        requests:
            cpu: 500m
            ephemeral-storage: 100Mi
            memory: 1Gi
        limits:
            cpu: 1000m
            ephemeral-storage: 500Mi
            memory: 2Gi

nodeSelector: {}

tolerations: []

labels: {}
annotations: {}
topologySpreadConstraints: []

affinity:
    podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                  topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                      matchExpressions:
                          - key: "app.kubernetes.io/part-of"
                            operator: "In"
                            values:
                                - "mxe"
                          - key: "app.kubernetes.io/component"
                            operator: "In"
                            values:
                                - "eric-mxe-gui"
                          - key: "app.kubernetes.io/instance"
                            operator: "In"
                            values:
                                - "{{ .Release.Name }}"

imageCredentials:
    registry:
        url:
        pullSecret:
    repoPath:
    guiService:
        repoPath:
        registry:
          url:
          pullSecret:
          imagePullPolicy:

productInfo:
    # R-State of the product. R State should match helm chart version (3.1.0 -> R2A)
    # To automate it when packaging the helm chart rstate can be generated
    # and below value replaced with correct R-State
    rstate: "-"

images:
    guiService:
        name: "mxe/eric-mxe-gui"
        tag: "VERSION"

updateStrategy:
    type: "RollingUpdate"
    rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

# DR-D1121-011 - Present in Top Level Helm Chart Values.yaml
# global:
#   registry:
#     url: "armdocker.rnd.ericsson.se"
#     pullSecret:
#   mxeApiTlsSecretName:
#   mxeApiHostname:
#   mxeDisableDefaultIngressControllerUse: false

legalWarningMessage: ""

probes:
    mxeGui:
        livenessProbe:
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
        readinessProbe:
            initialDelaySeconds: 0
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1

terminationGracePeriodSeconds: 30

podPriority:
    mxeGui:
        priorityClassName:

mode: default
uiApps:
    training: true
    exploration: true
    workflow: true
prometheusBasePath: /v1/prometheus/api/v1
modelServicePath: /model-endpoints/{id}
gas:
    enable: false
    workspace: workspace-gui
    appExternalHost:

serviceMesh:
    enabled: true
    tlsMode: ISTIO_MUTUAL

# DR-D1123-127 -  ADP services shall define AppArmor profile
appArmorProfile:
    type:
    localhostProfile:

# ADP services shall define Seccomp profile
seccompProfile:
  type: RuntimeDefault
  localhostProfile: