apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-mxe-gatekeeper.secret-eric-sec-access-mgmt-creds" . | quote }}
  labels:
    {{- $remove := include "eric-mxe-gatekeeper.remove-after-install" . | fromYaml -}}
    {{- $component := printf "%s" "app.kubernetes.io/component: gatekeeper-eric-sec-access-mgmt-creds"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-gatekeeper.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-gatekeeper.labels" . | fromYaml -}}
    {{- include "eric-mxe-gatekeeper.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels $remove )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: pre-install"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-gatekeeper.hook-weight" -5 | fromYaml -}}
    {{- $annotations := include "eric-mxe-gatekeeper.annotations" . | fromYaml -}}
    {{- include "eric-mxe-gatekeeper.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
type: Opaque
stringData:
  {{- if eq (include "eric-mxe-gatekeeper.secret-eric-sec-access-mgmt-creds" . | quote) (.Values.keycloak.realm.master.secret.secretName | quote ) }}
  kcadminid: {{ .Values.keycloak.realm.master.secret.kcadminid | quote }}
  kcpasswd: {{ .Values.keycloak.realm.master.secret.kcpasswd | quote }}
  {{- end }}
  pguserid: {{ .Values.database.createdUser.pguserid | quote }}
  {{- if .Values.database.createdUser.pgpasswd }}
  pgpasswd: {{ .Values.database.createdUser.pgpasswd | quote -}}
  {{- else }}
  pgpasswd: {{ randAscii 24 | b64enc | quote -}}
  {{- end }}
