{{- if not .Values.keycloak.realm.mxe.secret.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-mxe-gatekeeper.secret-realm-mxe" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: gatekeeper-secret-realm-mxe"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-gatekeeper.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-gatekeeper.labels" . | fromYaml -}}
    {{- include "eric-mxe-gatekeeper.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-gatekeeper.annotations" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.realm.mxe.secret.username | quote }}
  password: {{ .Values.keycloak.realm.mxe.secret.password | quote }}
{{- end }}
