apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eric-mxe-gatekeeper.role" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: gatekeeper-role"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-gatekeeper.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-gatekeeper.labels" . | fromYaml -}}
    {{- include "eric-mxe-gatekeeper.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-gatekeeper.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - namespaces
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resourceNames:
      - "{{ .Values.keycloak.statefulset.name }}-0"
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - "" 
    resourceNames:
      - "{{ .Values.keycloak.statefulset.name }}-0"
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resourceNames:
      - {{ .Values.keycloak.statefulset.name | quote }}
    resources:
      - statefulsets
    verbs:
      - get
      - watch
      - list
