apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-mxe-gatekeeper.secret-config" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: gatekeeper-secret-config"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-gatekeeper.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-gatekeeper.labels" . | fromYaml -}}
    {{- include "eric-mxe-gatekeeper.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-gatekeeper.annotations" . | nindent 4 }}
type: Opaque
stringData:
  gatekeeper.yaml: |-
    client-id: mxe-client
    client-secret:
    discovery-url: {{ include "eric-mxe-gatekeeper.oauth-api-host-path-url" . -}}/auth/realms/mxe
    preserve-host: true
    enable-token-header: false
    enable-authorization-header: true
    enable-authorization-cookies: false
    enable-default-deny: true
    server-read-timeout: 0
    server-write-timeout: 0
    upstream-keepalives: true
    upstream-timeout: 0
    upstream-response-header-timeout: 0
    enable-refresh-tokens: true
    encryption-key: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
    enable-metrics: true
    http-only-cookie: true
    store-url: boltdb:////home/gatekeeper/store.db
    tls-cert: /run/secrets/cert/tls.crt
    tls-private-key: /run/secrets/cert/tls.key
    sign-in-page: /etc/template/template.html
    listen: 0.0.0.0:3000
    upstream-url: http://{{- include "eric-mxe-gatekeeper.ingress-controller-host" . }}
    enable-logging: true
    enable-json-logging: true
    verbose: false
    scopes:
    - mxe-scope
    resources:
    - uri: /*
      require-any-role: true
    - uri: /auth/realms/mxe/account*
      require-any-role: true
    - uri: /auth*
      white-listed: true
    - uri: /v2/model-services*
      white-listed: false
    - uri: /v2*
      white-listed: true
    - uri: /legal/message.txt
      white-listed: true
