apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-mxe-gatekeeper.name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: gatekeeper"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-gatekeeper.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-gatekeeper.labels" . | fromYaml -}}
    {{- include "eric-mxe-gatekeeper.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations: {{ include "eric-mxe-gatekeeper.annotations" . | nindent 4 }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type | quote }}
  {{- else if .Values.global.mxeDisableDefaultIngressControllerUse }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- include "eric-mxe-gatekeeper.ipFamilies" . | nindent 2 }}
  {{- end }}
  selector:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "gatekeeper"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: https
      port: 3000
      targetPort: 3000
      {{- if .Values.global.mxeDisableDefaultIngressControllerUse }}
      nodePort: {{ .Values.service.httpsPort }}
      {{- end }}
