{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eric-mxe-prometheus.ingress-name" . | quote }}
  labels:
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-prometheus.ingress-name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-prometheus.labels" . | fromYaml -}}
    {{- include "eric-mxe-prometheus.mergeLabels" (dict "location" .Template.Name "sources" (list $name $labels )) | trim | nindent 4 }}
  annotations:
    {{- $annotations := include "eric-mxe-prometheus.annotations" . | fromYaml -}}
    {{- $ingressAnn := include "eric-mxe-prometheus.ingress-annotations" . | fromYaml -}}
    {{- include "eric-mxe-prometheus.mergeAnnotations" (dict "location" .Template.Name "sources" (list $ingressAnn $annotations)) | trim | nindent 8 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass | quote }}
  defaultBackend:
    service:
      name: {{ include "eric-mxe-prometheus.defaultbackend" . | quote }}
      port:
        name: "http"
  {{- include "eric-mxe-prometheus.ingress-tls" . | nindent 2 -}}
  rules:
    - http:
        paths:
        - path: /v1/prometheus(/|$)(.*)
          backend:
            service:
              name: eric-pm-server
              port:
                name:  {{ include "eric-mxe-prometheus.ingress-port-name" . | quote }}
          pathType: ImplementationSpecific
      {{- if or .Values.global.mxeApiHostname .Values.ingress.hostname }}
      host: {{ default .Values.global.mxeApiHostname .Values.ingress.hostname | quote }}
      {{- end }}
{{- end }}
