{{- if .Values.global.serviceMesh.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "eric-mxe-prometheus.name" . }}-se
  labels:
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-prometheus.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-prometheus.labels" . | fromYaml -}}
    {{- include "eric-mxe-prometheus.mergeLabels" (dict "location" .Template.Name "sources" (list $name $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-prometheus.annotations" . | nindent 4 }}
spec:
  hosts: 
  - {{ include "eric-mxe-prometheus.pm-service-host" . }}
  ports:
  - number: 9089
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
{{- end -}}