{{- if .Values.global.security.tls.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mxe.docker-configmap" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe-workflow"
    app.kubernetes.io/component: "mxe-workflow"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe.docker-configmap" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe.name" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- include "mxe.product-info" . | nindent 4 }}
data:
  Dockerfile: |
    {{ (tpl (.Files.Get "files/dockerfile.txt")  .) | nindent 4 }}
{{- end }}