{{- if .Values.global.security.tls.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mxe.docker-registry-secret-name" . }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "model-workflow-docker-registry-secret"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- include "mxe.product-info" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "mxe.docker-registry-config" . }}
{{- end }}