{{- if .Values.global.serviceMesh.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "eric-mxe-model-catalogue-service.minio-destinationRule" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-catalogue-service"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-model-catalogue-service.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-model-catalogue-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-catalogue-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-model-catalogue-service.annotations" . | nindent 4 }}
spec:
  host: eric-data-object-storage-mn
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 9000
      tls:
        mode: SIMPLE
        caCertificates: {{ include "eric-mxe-model-catalogue-service.egress-ca-cert" . }}
{{ end }}