{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eric-mxe-model-catalogue-service.ingress-file" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-catalogue-service-ingress-file"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-model-catalogue-service.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-model-catalogue-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-catalogue-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $annotations := include "eric-mxe-model-catalogue-service.annotations" . | fromYaml -}}
    {{- $ingressAnn := include "eric-mxe-model-catalogue-service.ingress-annotations" . | fromYaml -}}
    {{- include "eric-mxe-model-catalogue-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $annotations $ingressAnn)) | trim | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass | quote }}
  defaultBackend:
    service:
      name: {{ include "eric-mxe-model-catalogue-service.defaultbackend" . | quote }}
      port:
        name: "http"
  {{- include "eric-mxe-model-catalogue-service.ingress-tls" . | nindent 2 -}}
  rules:
    - http:
        paths:
          - path: /v1/models$
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "eric-mxe-model-catalogue-service.name" . | quote }}
                port:
                  name: "http"
      {{- if or .Values.global.mxeApiHostname .Values.ingress.hostname }}
      host: {{ default .Values.global.mxeApiHostname .Values.ingress.hostname | quote }}
      {{- end }}
{{ end }}