{{- if .Values.global.security.tls.enabled -}}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "eric-mxe-model-catalogue-service.name" . }}-pg-cert
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-catalogue-service"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-model-catalogue-service.name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-model-catalogue-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-catalogue-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-model-catalogue-service.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-mxe-model-catalogue-service.name" . }}-pg-cert
    certificateName: {{ include "eric-mxe-model-catalogue-service.pg-client-cert" . }}
    privateKeyName: {{ include "eric-mxe-model-catalogue-service.pg-private-key" . }}
  certificate:
    subject:
      cn: {{ include "eric-mxe-model-catalogue-service.name" . | replace "-" "" }}
    issuer:
      reference: {{  include "eric-mxe-model-catalogue-service.pg-ca-issuer" . | quote}}
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end -}}