apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-mxe-model-catalogue-service.name" . }}-post-delete-hook-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-catalogue-service-post-delete-hook-config"  | fromYaml -}}
    {{- $name := printf "%s: %s-%s" "app.kubernetes.io/name" (include "eric-mxe-model-catalogue-service.name" .) "post-delete-hook-config"  | fromYaml -}}
    {{- $labels := include "eric-mxe-model-catalogue-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-catalogue-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: post-delete"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-model-catalogue-service.hook-weight" 1 | fromYaml -}}
    {{- $annotations := include "eric-mxe-model-catalogue-service.annotations" . | fromYaml -}}
    {{- include "eric-mxe-model-catalogue-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
data:
  {{- (.Files.Glob "files/minio-cleanup.sh").AsConfig | nindent 2 }}
