{{- $global := fromJson (include "eric-mxe-model-training-service.global" .) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-mxe-model-training-service.name" . }}-post-delete-hook
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-training-service-post-delete-hook"  | fromYaml -}}
    {{- $name := printf "%s: %s-%s" "app.kubernetes.io/name" (include "eric-mxe-model-training-service.name" .) "post-delete-hook" | fromYaml -}}
    {{- $labels := include "eric-mxe-model-training-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-training-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: post-delete"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-model-training-service.hook-weight" 2 | fromYaml -}}
    {{- $annotations := include "eric-mxe-model-training-service.annotations" . | fromYaml -}}
    {{- include "eric-mxe-model-training-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      annotations:
        {{- $istioAnn := include "eric-mxe-model-training-service.istio-annotations" . | fromYaml -}}
        {{- $annotations := include "eric-mxe-model-training-service.annotations" . | fromYaml -}}
        {{- if .Values.appArmorProfile.type }}
        {{- $appArmor := printf "%s: %s" "container.apparmor.security.beta.kubernetes.io/minio-post-delete-hook" .Values.appArmorProfile.type | fromYaml -}}
        {{- include "eric-mxe-model-training-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $istioAnn $appArmor $annotations)) | trim | nindent 8 }}
        {{- else -}}
        {{- include "eric-mxe-model-training-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $istioAnn $annotations)) | trim | nindent 8 }}
        {{- end }}
      labels:
        {{- include "eric-mxe-model-training-service.istio-labels" .  | indent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if include "eric-mxe-model-training-service.podPriority" . }}
      priorityClassName: {{- include "eric-mxe-model-training-service.podPriority" . | indent 2 }}
      {{- end }}
      tolerations: {{ include "eric-mxe-model-training-service.merge-tolerations" (dict "root" . "podbasename" "eric-mxe-model-training-service") | nindent 8}}
      containers:
        - name: minio-post-delete-hook
          {{- with (index .Values "imageCredentials" "minio-cli") }}
          image: "{{ include "eric-mxe-model-training-service.setImageRepo" (list $ .registry.url .repoPath "minio-cli") }}{{ index $.Values "images" "minio-cli" "name" }}:{{ index $.Values "images" "minio-cli" "tag" }}"
          {{- end }}
          imagePullPolicy: "{{ include "eric-mxe-model-training-service.registryImagePullPolicy" (list . (index .Values "images" "minio-cli" "pullPolicy")) }}"
          command: ["/bin/bash", "/etc/cleanup/minio-cleanup.sh"]
          volumeMounts:
            - mountPath: "/etc/cleanup/"
              name: cleanup-scripts
            - mountPath: /run/secrets/config
              name: minio-configuration
            {{ include "eric-mxe-model-training-service.minio-init-volume-mounts" . | nindent 12 }}
          env:
            - name: MINIO_URL
              value: {{ include "eric-mxe-model-training-service.minio-url" . | quote }}
            - name: MINIO_TRAINING_JOB_RESULT_SERVICE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "eric-mxe-model-training-service.training-job-result-service-minio-user-secret-name" . | quote }}
                  key: accesskey
            - name: MINIO_MODEL_JOB_RESULT_INSTANCE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "eric-mxe-model-training-service.training-job-result-instance-minio-user-secret-name" . | quote }}
                  key: accesskey
            - name: MINIO_MODEL_PACKAGE_SERVICE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "eric-mxe-model-training-service.training-package-service-minio-user-secret-name" . | quote }}
                  key: accesskey
            - name: MINIO_MODEL_PACKAGE_INSTANCE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "eric-mxe-model-training-service.training-package-instance-minio-user-secret-name" . | quote }}
                  key: accesskey
            - name: USERS_TO_DELETE
              value: "$(MINIO_TRAINING_JOB_RESULT_SERVICE_ACCESS_KEY),$(MINIO_MODEL_JOB_RESULT_INSTANCE_ACCESS_KEY),$(MINIO_MODEL_PACKAGE_SERVICE_ACCESS_KEY),$(MINIO_MODEL_PACKAGE_INSTANCE_ACCESS_KEY)"
            - name: TRAINING_JOB_RESULTS_MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "eric-mxe-model-training-service.training-job-result-service-minio-user-secret-name" . | quote }}
                  key: bucket
            - name: TRAINING_PACKAGE_SERVICE_MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "eric-mxe-model-training-service.training-package-service-minio-user-secret-name" . | quote }}
                  key: bucket
            - name: BUCKETS_TO_DELETE
              value: "$(TRAINING_JOB_RESULTS_MINIO_BUCKET),$(TRAINING_PACKAGE_SERVICE_MINIO_BUCKET)"
            - name: SERVICE_MESH_MTLS_ENABLED
              value: {{ .Values.global.security.tls.enabled | quote }}
          resources:
            {{- toYaml .Values.resources.minioCli | trim | nindent 12 }}
          {{- include "eric-mxe-model-training-service.post-delete-hook-security-context" . | nindent 10 }}
      restartPolicy: OnFailure
      volumes:
      - configMap:
          name: {{ include "eric-mxe-model-training-service.name" . }}-post-delete-hook-config
        name: cleanup-scripts
      - name: minio-configuration
        secret:
          secretName: {{ .Values.minio.adminSecretName | quote }}
      - name: mxe-mc-home
        emptyDir: {}
      {{- if .Values.global.security.tls.enabled }}
      - name: trusted-ca
        secret:
          secretName: eric-sec-sip-tls-trusted-root-cert
      {{- end }}
      {{- include "eric-mxe-model-training-service.image-pull-secrets" . | nindent 6 }}
      {{- if (or .Values.nodeSelector $global.nodeSelector) }}
      nodeSelector: {{- include "eric-mxe-model-training-service.nodeSelector" . | nindent 8 }}
      {{- end }}