{{- if not .Values.minio.userTrainingPackageServiceSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-mxe-model-training-service.training-package-service-minio-user-secret-name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: model-training-service-ms-service-minio-user-secret"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-model-training-service.training-package-service-minio-user-secret-name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-model-training-service.labels" . | fromYaml -}}
    {{- include "eric-mxe-model-training-service.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: pre-install"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-model-training-service.hook-weight" -5 | fromYaml -}}
    {{- $annotations := include "eric-mxe-model-training-service.annotations" . | fromYaml -}}
    {{- include "eric-mxe-model-training-service.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
type: Opaque
data:
  accesskey: {{ include "eric-mxe-model-training-service.training-package-service-minio-user-name" . | b64enc | quote }}
  {{- if .Values.minio.trainingp.service.secretkey }}
  secretkey: {{ .Values.minio.trainingp.service.secretkey | b64enc | quote }}
  {{- else }}
  secretkey: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  bucket: {{ include "eric-mxe-model-training-service.training-package-minio-bucket" . | b64enc | quote }}
{{- end }}
