apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-mxe-serving-upgrade-jobs.preupgrade-cleanup-configmap" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: preupgrade-cleanup-configmap"  | fromYaml -}}
    {{- $labels := include "eric-mxe-serving-upgrade-jobs.labels" . | fromYaml -}}
    {{- include "eric-mxe-serving-upgrade-jobs.mergeLabels" (dict "location" .Template.Name "sources" (list $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: pre-upgrade"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-serving-upgrade-jobs.hook-weight" 0 | fromYaml -}}
    {{- $annotations := include "eric-mxe-serving-upgrade-jobs.annotations" . | fromYaml -}}
    {{- include "eric-mxe-serving-upgrade-jobs.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
data:
  {{- (.Files.Glob "files/preupgrade-cleanup/run.sh").AsConfig | nindent 2 }}
