# Default values for mxe training.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# DR-D1121-011 - Includes global vales of sub-charts
global:
  internalRegistry:
    username: admin
    password: ""
  pullSecret:
  registry:
    url:
    pullSecret:
    imagePullPolicy: IfNotPresent
    repoPath:   
  mxeApiTlsSecretName:
  mxeApiHostname:
  mxeIamCaSecretName: iam-ca-cert
  mxeDisableDefaultIngressControllerUse: false
  mxeClusterDomain: cluster.local
  fsGroup:
    manual: 10000
    namespace: false
  mxeLogControlConfigMap: mxe-commons-log-control-configmap
  mxePrometheusPath: /actuator/prometheus
  mxePrometheusPort: '8081'
  mxePrometheusScrape: 'true'
  mxePrometheusScrapeRole: pod 
  mxePrometheusScrapeInterval: 15s
  internalIPFamily:
  security:
    tls:
      enabled: false
  serviceMesh:
    enabled: true
    annotations:
      serviceMesh:
    egress:
      ca:
        secretName: egress-ca-secret
        caCertsPath: /etc/istio/egress-ca-certs/
        caCertificates: ca.crt
        genSecretName: eric-sec-sip-tls-trusted-root-cert
        readonly: true
      lcmRegistry:
        enabled: true
        serviceName: eric-lcm-container-registry-registry
        secretName: egress-lcm-secret
        certsPath: /etc/istio/lcm/egress-certs/
        genSecretName: eric-lcm-container-registry-client-cert
        clientCertificate: clicert.pem
        privateKey: cliprivkey.pem
        optional: true
        readonly: true
        tlsMode: MUTUAL
      iam:
        enabled: true
        serviceName: eric-sec-access-mgmt-http
        secretName: egress-secret
        certsPath: /etc/istio/egress-certs/
        genSecretName: eric-sec-access-mgmt-iam-int-client-cert
        clientCertificate: clicert.pem
        privateKey: cliprivkey.pem
        optional: true
        readonly: true
        tlsMode: MUTUAL
        certificateCN: adp-iam-aa-client
        caIssuer: eric-sec-access-mgmt-iam-client-ca
      pmServer:
        enabled: true
        serviceName: eric-pm-server
        caIssuer: eric-pm-server-query-ca
        secretName: egress-pm-secret
        certsPath: /etc/istio/pm/egress-certs/
        genSecretName: eric-pm-server-query-cert
        clientCertificate: clicert.pem
        privateKey: cliprivkey.pem
        optional: true
        readonly: true
      postgres:
        serviceName: eric-data-document-database-pg
        caIssuer: eric-data-document-database-pg-client-ca
        clientCertificate: clicert.pem
        privateKey: cliprivkey.pem
  labels: {}
  annotations: {}
  nodeSelector: {}

productInfo:
# R-State of the product. R State should match helm chart version (3.1.0 -> R2A)
# To automate it when packaging the helm chart rstate can be generated
# and below value replaced with correct R-State
  rstate:

# Dependent 3pps must be configured below


eric-mxe-pre-upgrade-job:
  statusCheckInterval: 60
  includeReleaseNameSelector: true
  nameOverride: eric-mxe-training-pre-upgrade-job


eric-mxe-model-training-service:
  resources:
    modelService:
      requests:
        cpu: 100m
        memory: 1Gi
        ephemeral-storage: 50Mi
      limits:
        cpu: 400m
        memory: 2Gi
        ephemeral-storage: 100Mi
    kubernetesModifier:
      limits:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 100Mi
      requests:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 100Mi
    dbInit:
      limits:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 100Mi
      requests:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 100Mi
    minioCli:
      limits:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 100Mi
      requests:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 100Mi