apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-mxe-serving-pre-upgrade-job.serviceaccount" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
   {{- $component := printf "%s" "app.kubernetes.io/component: pre-upgrade-job-service-account"  | fromYaml -}}
    {{- $labels := include "eric-mxe-serving-pre-upgrade-job.labels" . | fromYaml -}}
    {{- include "eric-mxe-serving-pre-upgrade-job.mergeLabels" (dict "location" .Template.Name "sources" (list $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: pre-upgrade"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: before-hook-creation"  | fromYaml -}}
    {{- $hookWeight := include "eric-mxe-serving-pre-upgrade-job.hook-weight" -5 | fromYaml -}}
    {{- $annotations := include "eric-mxe-serving-pre-upgrade-job.annotations" . | fromYaml -}}
    {{- include "eric-mxe-serving-pre-upgrade-job.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $hookWeight $annotations)) | trim | nindent 4 }}
