{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "eric-mxe-pypiserver.name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: pypiserver-secret"  | fromYaml -}}
    {{- $labels := include "eric-mxe-pypiserver.labels" . | fromYaml -}}
    {{- include "eric-mxe-pypiserver.mergeLabels" (dict "location" .Template.Name "sources" (list $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-pypiserver.annotations" . | nindent 4 }}
stringData:
  .htpasswd: |-
    {{- range $key, $value := .Values.auth.credentials }}
    {{ $key }}:{{ $value }}
    {{- end }}
{{- end }}
