apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-mxe-seldon-service-account.engine-name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: seldon-service-account-engine"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-seldon-service-account.engine-name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-seldon-service-account.labels" . | fromYaml -}}
    {{- include "eric-mxe-seldon-service-account.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-seldon-service-account.annotations" . | nindent 4 }}
{{ include "eric-mxe-seldon-service-account.image-pull-secrets" . }}
automountServiceAccountToken: false
