{{- if .Values.global.serviceMesh.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mxe-deployer.post-install-hook-certificate-sidecar-name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "post-install-hook-certificate-sidecar-role"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ include "mxe-deployer.post-install-hook-certificate-sidecar-name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "mxe-deployer.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- include "mxe-deployer.product-info" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "apps"
    resources:
      - "deployments/scale"
    verbs:
      - patch
{{- end -}}
