kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "eric-mxe-jupyterhub.hub-config-name" . | quote }}
  labels:
    app.kubernetes.io/component: "jupyterhub-hub-configmap"
    app.kubernetes.io/name: {{ include "eric-mxe-jupyterhub.hub-config-name" . | quote }}
    {{- include "eric-mxe-jupyterhub.labels" . | nindent 4 }}
  annotations: {{ include "eric-mxe-jupyterhub.annotations" . | nindent 4 }}
data:
{{- $values := pick .Values "auth" "cull" "custom" "debug" "hub" "singleuser" }}
{{- /* trim secret values. Update here if new secrets are added! */ -}}
{{- /* make a copy of values.auth to avoid modifying the original */ -}}
{{- $_ := set $values "auth" (merge dict .Values.auth) }}
{{- $_ := set $values.auth "state" (omit $values.auth.state "cryptoKey") }}
{{- range $key, $auth := .Values.auth }}
  {{- if typeIs "map[string]interface {}" $auth }}
    {{- if (or $auth.clientSecret $auth.password) }}
      {{- $_ := set $values.auth $key (omit $auth "clientSecret" "password") }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $_ := set $values "hub" (omit $values.hub "cookieSecret" "extraEnv" "extraConfigMap") -}}
{{- $_ := set $values.hub "services" dict }}
{{- range $key, $service := .Values.hub.services }}
  {{- if $service.apiToken }}
    {{- $_ := set $values.hub.services $key (omit $service "apiToken") }}
  {{- end }}
{{- end }}

{{- /* copy values.singleuser */ -}}
{{- $_ := set $values "singleuser" (omit .Values.singleuser "imagePullSecret" ) }}
{{- $_ := set $values.singleuser.image "name" (printf "%s%s" (include "eric-mxe-jupyterhub.setImageRepo" (list . .Values.imageCredentials.singleuser.registry.url .Values.imageCredentials.singleuser.repoPath "singleuser")) .Values.images.singleuser.name ) }}
{{- $_ := set $values.singleuser.networkTools.image "name" (printf "%s%s" (include "eric-mxe-jupyterhub.setImageRepo" (list . .Values.imageCredentials.networkTools.registry.url .Values.imageCredentials.networkTools.repoPath "networkTools")) .Values.images.networkTools.name ) }}

{{- /* set MXE labels on singleuser pods */ -}}
{{- $_ := set $values.singleuser.extraLabels "app.kubernetes.io/instance" .Release.Name }}

{{- /* set MXE pod antiaffinity on singleuser pods */ -}}
{{- $_ := set (index ((index .Values.singleuser.extraPodAntiAffinity.preferred 0).podAffinityTerm.labelSelector.matchExpressions) 2) "values" (list .Release.Name) }}

{{- /* preserve behavior of deprecated hub.extraConfigMap */ -}}
{{- $_ := set $values "custom" (merge dict $values.custom .Values.hub.extraConfigMap) }}
{{- /* passthrough subset of Chart / Release */ -}}
{{- $_ := set $values "Chart" (dict "Name" .Chart.Name "Version" .Chart.Version) }}
{{- $_ := set $values "Release" (pick .Release "Name" "Namespace" "Service") }}
  {{- include "eric-mxe-jupyterhub.name-templates" . | nindent 2 }}

  {{- /*
    Glob files to allow them to be mounted by the hub pod

    jupyterhub_config: |
      multi line string content...
    z2jh.py: |
      multi line string content...
  */}}
  {{- (.Files.Glob "files/hub/*").AsConfig | nindent 2 }}
  values.yaml: |
    {{- $values | toYaml | nindent 4 }}
  pipConf: |
{{- tpl (.Files.Get "files/pip.conf") $ | nindent 4 }}