{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-mxe-jupyterhub.hub-service-account-name" . | quote }}
  labels:
    app.kubernetes.io/component: "jupyterhub-hub-service-account"
    app.kubernetes.io/name: {{ include "eric-mxe-jupyterhub.hub-service-account-name" . | quote }}
    {{- include "eric-mxe-jupyterhub.labels" . | nindent 4 }}
  annotations: {{ include "eric-mxe-jupyterhub.annotations" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "eric-mxe-jupyterhub.hub-role-name" . | quote }}
  labels:
    app.kubernetes.io/component: "jupyterhub-hub-role"
    app.kubernetes.io/name: {{ include "eric-mxe-jupyterhub.hub-role-name" . | quote }}
    {{- include "eric-mxe-jupyterhub.labels" . | nindent 4 }}
  annotations: {{ include "eric-mxe-jupyterhub.annotations" . | nindent 4 }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "persistentvolumeclaims", "secrets", "services"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "eric-mxe-jupyterhub.hub-role-binding-name" . | quote }}
  labels:
    app.kubernetes.io/component: "jupyterhub-hub-role-binding"
    app.kubernetes.io/name: {{ include "eric-mxe-jupyterhub.hub-role-binding-name" . | quote }}
    {{- include "eric-mxe-jupyterhub.labels" . | nindent 4 }}
  annotations: {{ include "eric-mxe-jupyterhub.annotations" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-mxe-jupyterhub.hub-service-account-name" . | quote }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "eric-mxe-jupyterhub.hub-role-name" . | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
