apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-mxe-jupyterhub.hub-service-name" . | quote }}
  labels:
    app.kubernetes.io/component: "jupyterhub-hub-service"
    app.kubernetes.io/name: {{ include "eric-mxe-jupyterhub.hub-service-name" . | quote }}
    {{- include "eric-mxe-jupyterhub.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.global.serviceMesh.enabled -}}
    {{- if not (index .Values.hub.service.annotations "prometheus.io/scrape") }}
    prometheus.io/scrape: "true"
    {{- end }}
    {{- if not (index .Values.hub.service.annotations "prometheus.io/path") }}
    prometheus.io/path: {{ .Values.hub.baseUrl | trimSuffix "/" }}/hub/metrics
    {{- end }}
    {{- if not (index .Values.hub.service.annotations "prometheus.io/port") }}
    prometheus.io/port: "8081"
    {{- end }}
    {{- end }}
    {{- with .Values.hub.service.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- include "eric-mxe-jupyterhub.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [ {{ .Values.global.internalIPFamily | quote }} ]
  {{- end }}
  {{- end }}
  {{- with .Values.hub.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    app.kubernetes.io/part-of: "mxe"
    app.kubernetes.io/component: "jupyterhub-hub"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    {{- include "eric-mxe-jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    - name: hub
      port: 8081
      targetPort: http
      {{- with .Values.hub.service.ports.nodePort }}
      nodePort: {{ . }}
      {{- end }}

    {{- with .Values.hub.service.extraPorts }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
