apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eric-mxe-upgrade-jobs.preupgrade-cleanup-cluster-role" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: preupgrade-cleanup-cluster-role"  | fromYaml -}}
    {{- $labels := include "eric-mxe-upgrade-jobs.labels" . | fromYaml -}}
    {{- include "eric-mxe-upgrade-jobs.mergeLabels" (dict "location" .Template.Name "sources" (list $component $labels )) | trim | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- include "eric-mxe-upgrade-jobs.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - "delete"
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - "delete"
      - "deletecollection"
