apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-mxe-spark.post-install-hook-name" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: post-install-hook"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-spark.post-install-hook-name" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-spark.labels" . | fromYaml -}}
    {{- include "eric-mxe-spark.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- $hook := printf "%s" "helm.sh/hook: post-install,post-upgrade"  | fromYaml -}}
    {{- $hookDeletePolicy := printf "%s" "helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation"  | fromYaml -}}
    {{- $annotations := include "eric-mxe-spark.annotations" . | fromYaml -}}
    {{- include "eric-mxe-spark.mergeAnnotations" (dict "location" .Template.Name "sources" (list $hook $hookDeletePolicy $annotations)) | trim | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      annotations:
        {{- $istioAnn := include "eric-mxe-spark.istio-annotations" . | fromYaml -}}
        {{- $securityAnn := include "eric-mxe-spark.security-annotations" . | fromYaml -}}
        {{- $annotations := include "eric-mxe-spark.annotations" . | fromYaml -}}
        {{- include "eric-mxe-spark.mergeAnnotations" (dict "location" .Template.Name "sources" (list $istioAnn $securityAnn $annotations)) | trim | nindent 8 }}
      labels:
        {{- $labels := include "eric-mxe-spark.labels" . | fromYaml -}}
        {{- $istioLab := include "eric-mxe-spark.istio-labels" . | fromYaml -}}
        {{- include "eric-mxe-spark.mergeLabels" (dict "location" .Template.Name "sources" (list $labels $istioLab )) | trim | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eric-mxe-spark.post-install-hook-service-account" . | quote }}
      containers:
        - name: restart-spark-deployment
          {{- with (index .Values "imageCredentials" "kubernetes-modifier") }}
          image: "{{ include "eric-mxe-spark.setImageRepo" (list $ .registry.url .repoPath "kubernetes-modifier") }}{{ index $.Values "images" "kubernetes-modifier" "name" }}:{{ index $.Values "images" "kubernetes-modifier" "tag" }}"
          {{- end }}
          imagePullPolicy: {{ include "eric-mxe-spark.registryImagePullPolicy" (list . (index .Values "imageCredentials" "kubernetes-modifier" "registry" "imagePullPolicy")) }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources.kubernetesModifier | trim | nindent 12 }}
          securityContext:
            {{- include "eric-mxe-spark.post-install-hook-security-context" . | nindent 12 }}
          volumeMounts:
            - mountPath: "/etc/kubernetes-run-script/"
              name: kubernetes-run-script
      {{- include "eric-mxe-spark.tolerations" . | nindent 6 }}
      tolerations: {{ include "eric-mxe-spark.merge-tolerations" (dict "root" . "podbasename" "eric-mxe-spark") | nindent 8}}
      restartPolicy: Never
      volumes:
      - configMap:
          name: {{ include "eric-mxe-spark.post-install-hook-configmap" . | quote }}
        name: kubernetes-run-script
      {{- include "eric-mxe-spark.image-pull-secrets" . | nindent 6 }}
