apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-mxe-spark.post-install-hook-role-binding" . | quote }}
  labels:
    {{- $component := printf "%s" "app.kubernetes.io/component: post-install-hook-role-binding"  | fromYaml -}}
    {{- $name := printf "%s: %s" "app.kubernetes.io/name" (include "eric-mxe-spark.post-install-hook-role-binding" .)  | fromYaml -}}
    {{- $labels := include "eric-mxe-spark.labels" . | fromYaml -}}
    {{- include "eric-mxe-spark.mergeLabels" (dict "location" .Template.Name "sources" (list $name $component $labels )) | trim | nindent 4 }}
  annotations:
    {{- include "eric-mxe-spark.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eric-mxe-spark.post-install-hook-role" . | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-mxe-spark.post-install-hook-service-account" . | quote }}
    namespace: {{ .Release.Namespace | quote }}
